---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: Testing
    tekton.dev/displayName: vse-framework
    tekton.dev/tags: 'golang, vse-sync-testsuite'
  name: deploy-vse-sync-test
spec:
  description: This task runs the vse-sync-testsuite image.
  params:
    - default: 'quay.io/redhat-partner-solutions/vse-sync-test:latest'  # yamllint disable rule:line-length
      description: Image for test suite
      name: test-image
      type: string
    - description: |
        The tag for the image you want to run
      name: kubeconfig_secret
      type: string
    - default: /usr/vse/kubeconfig
      description: |
        Path that the kubeconfig will be mounted into
      name: kubeconfig_secret_dest_path
      type: string
    - default: /workspace/reports/vse-sync-testsuite.json
      description: |
        Path of test results report
      name: report_path
      type: string
  steps:
    - image: 'quay.io/redhat-partner-solutions/vse-sync-test:latest'
      name: run-ptp-suite
      script: |
        #!/bin/sh

        ./vse-sync-test/hack/e2e.sh \
          -k /usr/vse/kubeconfig/kubeconfig \
          -d 1250

        chmod a+r $(params.report_path)

        echo $?
      volumeMounts:
        - mountPath: $(params.kubeconfig_secret_dest_path)
          name: kubeconfig-secret
    # - image: "quay.io/toolhippie/jq:latest"
    #   name: process-results
    #   resources: {}
    #   # Tried to find a way to wrap this but it kept breaking
    #   # yamllint disable
    #   script: >
    #     #!/bin/sh

    #     if [ ! -f $(params.report_path) ]; then
    #       exit 1;
    #     fi

    #     jq -r '.[] | select(.SuiteSucceeded  == false) | .SpecReports[] | select(has("Failure")) | [.ContainerHierarchyTexts , .LeafNodeText] | flatten | join(" / ")'  $(params.report_path) > /workspace/reports/sync-test-failures;
    #   # yamllint enable
  volumes:
    - name: kubeconfig-secret
      secret:
        secretName: $(params.kubeconfig_secret)
  workspaces:
    - mountPath: /workspace/reports
      name: report
