---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vse-cicd-catalog

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"

resources:
    - catalog-ns.yaml
    - git-clone.yaml
    - list-directory.yaml
    - send-to-gchat.yaml
    - write-file.yaml
    - get-kubeconfig.yaml
    - buildah.yaml
    - set-tag.yaml
    - deploy-gotests.yaml
    - deploy-ptp-gotests.yaml
    - copy-from-workspace.yaml
    - send-report-to-gchat.yaml
    - deploy-vse-sync-testsuite.yaml
    - deploy-vse-sync-test.yaml
    - argocd-task-sync-and-wait.yaml
    - https://api.hub.tekton.dev/v1/resource/tekton/task/openshift-client/0.2/raw
