---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-to-gchat-space
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Messaging
    tekton.dev/tags: messaging
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    This task post a simple message to a gchat space.
  params:
    - name: webhook-url
      type: string
      description: url for gchat webhook
    - name: message
      type: string
      description: plain text message
  steps:
    - name: post
      image: registry.access.redhat.com/ubi9/ubi:9.1.0-1782
      # yamllint disable rule:line-length
      script: |
        #!/bin/sh
        curl -X POST -H 'Content-type: application/json'  --data '{"text":"$(params.message)"}' "$(params.webhook-url)"
      # yamllint enable rule:line-length
