---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-vse-sync-test-run
  labels:
    tekton.dev/pipeline: run-vse-sync-test
spec:
  serviceAccountName: pipeline-credentials-sa
  # serviceAccountName: robot-docker-basic
  params:
    - name: kubeconfig-secret
      value: falcon-admin-kubeconfig
    - name: kubeconfig-namespace
      value: falcon
    - name: kubeconfig-secret-dest
      value: falcon-admin-kubeconfig
  pipelineRef:
    name: run-vse-sync-test
