---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ArgoCD
    patch: |-
      - op: replace
        path: /spec/repo/initContainers/0/image
        value: registry.redhat.io/openshift4/ztp-site-generate-rhel8:v4.11
